### ISSUE TITLE
USER STORY: Admin panel 

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#1]
As a **Site owner** I can **access the admin panel**, so I can **see and update all of the informations, accept comments and remove inappropriate or spammy blog posts and comments, delete users.**

### Acceptance criteria

- Must be able to log in as a backend's admin
- Must be able to add, edit, save and delete the content and users

### Tasks

- [x] Create a SuperUser in terminal (backend)
- [x] Assign an admin link
- [x] Check if Admin is able to successfully log in and make changes
