### ISSUE TITLE
USER STORY:  Deleting account

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#14]
As a **User** I can **delete my profile**, so **it will be removed from the database**

### Acceptance criteria

- User must be logged in to their account
- Users must be able to see the delete button in order to use it
- User must confirm his decision on deleting their account by clicking on modal's button

### Tasks

- [ ] Add "delete" CRUD logic to the User's profile
- [ ] Display the "Delete" button to frontend for the User
- [ ] Add styling to the "Delete" button so it  stands out with warning colours which may prevent User from accidental click
- [ ] Add and style the confirmation pop up modal
