### ISSUE TITLE
USER STORY: Editing profile

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#16]
As a **User** I can **edit my profile**, so I can **keep the information upto date**

### Acceptance criteria

- Users must be logged in
- When users viewing their  profile
 they can see an edit button
- when clicking on the button they'll be taken to an editing page

### Tasks

- [x] Create a function for users to edit their own profile
- [x] create a page where users can edit the information within their profile
- [x] Add a button to a users profile that only displays when they are logged in and viewing their own profile
