### ISSUE TITLE
USER STORY: Reset password

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#17]
As a **User** I can **reset my password**, so I can **access my account even if I have forgotten my password**

### Acceptance criteria

- An option are available to reset the password if the user try to login with an incorrect password
- Users must enter their email they used to sign up
- Users receives an email with instructions on how they reset their password

### Tasks

- [ ] Create a link on the login to an reset password page
- [ ] Create from for users to enter their email
- [ ] Create an email that contains a link to reset the password
