### ISSUE TITLE
USER STORY:

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#17]
As a **Site owner** I can **access the admin panel**, so I can ** see and update all of the informations, accept comments and remove inappropriate or spammy blog posts and comments.**

### Acceptance criteria

- Must be able to log in as a backend's admin
- Must be able to add, edit, save and delete the content

### Tasks

- [ ] Create a SuperUser in terminal (backend)
- [ ] Assign an admin link
- [ ] Check if Admin is able to successfully log in and make changes
