### ISSUE TITLE
USER STORY: Edit and delete own comments

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#18]
As a **User** I can **edit and delete my comments**, so I can **manage my comments on the blog.**

### Acceptance criteria

- Editing and deleting is only allowed for the author of the comment and admin.
- Each comment has an "Edit" and "Delete" button visible to user.
- Clicking the "Edit" button opens a form allowing users to modify the comment content.
- Clicking the "Delete" button will prompt a message asking the user if they really want to delete their comment.
- Users can save the edited comment, and the changes are reflected in the comment details.

### Tasks
- [ ] create an edit and delete button and display them
- [ ] create a form for editing and a save button
- [ ] create an alert message to confirm if the users really want to delete their comment
