### ISSUE TITLE
USER STORY:  Contact the admin 

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#19]
As a **User** I can **use the contact form**, so I can **contact the admin of the blog**

### Acceptance criteria

-  The user does not need to be logged in to use the contact form
- The contact form is on its own page
- The contact form requires the user to fill in their email, name and texfield before they can send the form
- The user will get a confirmation message that their email have been sent successfully

### Tasks

- [ ] Create a contact page
- [ ] create a contact form 
- [ ] create a confirmation message
