### ISSUE TITLE
 USER STORY:  Comment notification

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#22]
As a **User** I can **be notified when someone comments on one of my blog posts**, so I can **respond if necessary**

### Acceptance criteria

- When users leaves a comment on a blog post, the owner of that post gets informed that someone has commented
- Users receive an email telling them that someone has commented on their post
-  The users can also see the comment in the email
-  Users also receives a link taking them to the relevant page so that they can respond if needed.

### Tasks

- [ ] Create a message center for each user
- [ ] Create a notification indicator that display’s when a user receives a new message
- [ ] Create an email template that can be utilised to populate an email body when an email is sent to a user informing them of the comment. The template should include a link to the recipe that was commented on, along with the comment details.
- [ ] Create an email trigger that sends an email to a user when someone comments on their recipe
