### ISSUE TITLE
USER STORY: Read and find easily accessible information about Charge Syndrome

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#3]
As a **Site User** I can **find readily available information about the syndrome**, so I can **read and gain a more in-depth understanding of what the syndrome entails.**

### Acceptance criteria

- The user must be able to take part in easy-to-read content about what the syndrome entails.
- The user should also be able to find links to various instances for more in-depth information about the syndrome.

### Tasks

- [ ] Create a page about the syndrome.
- [ ] Add easy-to-read content to the page.
- [ ] Add links to various instances for more in-depth information about the syndrome.
