### ISSUE TITLE
USER STORY:  About page

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#4]
As a **Site User** I can **easily access the "About" page**, so I can **find out the purpose of the blog and find a link to another page for more in-depth information.**

### Acceptance criteria

- The user can read the blogs purpose 
- The user should also be able to find a link to the page with more in-depth information.

### Tasks

- [x] Create an about page
- [x] Add easy-to-read content to the page.
- [x] Add a link to the page with more in-depth information about the syndrome.
