### ISSUE TITLE
USER STORY: Blog Post Submission

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#6]
As a **User** I can **upload a blog post with a title, content and an optional photo. 

### Acceptance criteria

- Users can upload a blog post with a title, content and an optional photo.
- Uploaded blog posts are stored in the database.

### Tasks

- [ ] Design a submission form with fields for title, content and photo upload.
- [ ]  Create a model for blog posts with fields for the above information.
- [ ]  Handle image uploads to Cloudinary and store the URL in the blog post model.
