### ISSUE TITLE
USER STORY: Blog Post Submission

### ISSUE THREAD

**Issue by Linnea87** [Linnea87/charge-together#7]
As a **User** I can **upload a blog post with a title, content and a photo.**

### Acceptance criteria
- Users must be logged in
- Users can upload a blog post with a title, content and a photo.
- Uploaded blog posts are stored in the database.

### Tasks

- [x] Design a submission form with fields for title, content and photo upload.
- [x]  Create a model for blog posts with fields for the above information.
- [x]  Handle image uploads to Cloudinary and store the URL in the blog post model.
